export const LOGIN: string = 'LOGIN'
export const SET_REPORTS: string = 'SET_REPORTS'
export const SET_REPORTS_COUNT: string = 'SET_REPORTS_COUNT'
export const SET_USER: string = 'SET_USER'
export const SET_TOKEN: string = 'SET_TOKEN'
